remote_theme: pages-themes/minimal@v0.2.0
logo: /images/photo.jpg
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      title: Michael Gunkoff's webpage
      description: I am Software Developer and Painter.
      layout: "default"
title: Michael Gunkoff's webpage
description: I am Software Developer and Painter.
social:
  linkedin: https://www.linkedin.com/in/kaatinga || linkedin
