remote_theme: pages-themes/minimal@v0.2.0
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      title: Kaatinga.Ru
      description: Michael Gunkoff's webpage
      layout: "default"
title: Kaatinga.Ru
description: Michael Gunkoff's webpage